language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_b8da2da49add_key -iv $encrypted_b8da2da49add_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
